In [1]:
import numpy as np

In [45]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [33]:

a= np.array([[1,2,3], [6,5,4]])
a.shape

(2, 3)

In [47]:
np.zeros([2,4],dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [49]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [53]:
np.full([3,4],6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [55]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [57]:
np.random.random([2,2])

array([[0.76971035, 0.04093972],
       [0.73391543, 0.00971095]])

In [73]:
np.random.seed(0)
np.random.random([2,2])

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [75]:
np.random.normal(0,1,[2,2])

array([[ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721]])

In [93]:
np.random.randint(0,10,(3,3,3))

array([[[2, 3, 3],
        [2, 3, 4],
        [1, 2, 9]],

       [[1, 4, 6],
        [8, 2, 3],
        [0, 0, 6]],

       [[0, 6, 3],
        [3, 8, 8],
        [8, 2, 3]]])

In [91]:
np.random.rand(2,2,3,4)

array([[[[0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
         [0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
         [0.3595079 , 0.43703195, 0.6976312 , 0.06022547]],

        [[0.66676672, 0.67063787, 0.21038256, 0.1289263 ],
         [0.31542835, 0.36371077, 0.57019677, 0.43860151],
         [0.98837384, 0.10204481, 0.20887676, 0.16130952]]],


       [[[0.65310833, 0.2532916 , 0.46631077, 0.24442559],
         [0.15896958, 0.11037514, 0.65632959, 0.13818295],
         [0.19658236, 0.36872517, 0.82099323, 0.09710128]],

        [[0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
         [0.97676109, 0.60484552, 0.73926358, 0.03918779],
         [0.28280696, 0.12019656, 0.2961402 , 0.11872772]]]])

In [129]:
print(x)


[[2 5 5]]


In [131]:
x.T

array([[2],
       [5],
       [5]])

In [141]:
x=np.random.randint(0,10,(1,3))
x1=np.random.randint(0,10,(1,3))
np.vstack((x,x1))

array([[5, 5, 5],
       [2, 5, 7]])

In [177]:
a= np.arange(3).reshape(1,3)

In [181]:
a

array([[0],
       [1],
       [2]])

In [147]:
a+5

array([5, 6, 7])

In [151]:
b=np.ones((3,3))

In [153]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [185]:
b*a.T

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.]])

In [187]:
c= np.arange(10000)


In [191]:
%timeit sum(c)
%timeit np.sum(sum)

622 μs ± 17.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
8.25 μs ± 365 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [211]:
np.mean(c)


4999.5

In [209]:
np.max(c)

9999

In [217]:
dog_hight= np.array([600,470,170,430,300])
np.std(dog_hight)

147.32277488562318

In [221]:
np.var(dog_hight)

21704.0

In [223]:
np.sqrt(np.var(dog_hight))

147.32277488562318

In [233]:
d=np.random.randint(0,10,(3,3))

In [235]:
d

array([[5, 9, 9],
       [2, 0, 9],
       [1, 9, 0]])

In [237]:
e=np.random.randint(0,10,(3,2))

In [239]:
e

array([[6, 0],
       [4, 8],
       [4, 3]])

In [241]:
d@e

array([[102,  99],
       [ 48,  27],
       [ 42,  72]])

In [249]:
np.random.seed(0)
sale_amounts=np.random.randint(20,size=(5,3))

In [251]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [257]:
import pandas as pd
sale = pd.DataFrame(sale_amounts,index=["Mon","Tue","Wed","Thu","Fri"],columns=["AM","PB","CB"])

In [259]:
sale

AM  PB  CB
Mon  12  15   0
Tue   3   3   7
Wed   9  19  18
Thu   4   6  12
Fri   1   6   7

In [261]:
price= np.array([5,8,12])


In [263]:
price


array([ 5,  8, 12])

In [269]:
butter_price = pd.DataFrame(price.reshape(1,3),index=["Price"],columns=["AM","PB","CB"])

In [271]:
butter_price

AM  PB  CB
Price   5   8  12

In [275]:
total_price = sale@butter_price.T

In [279]:
total_price

Price
Mon    180
Tue    123
Wed    413
Thu    212
Fri    137

In [283]:
sale["total"]=total_price

In [285]:
sale

AM  PB  CB  total
Mon  12  15   0    180
Tue   3   3   7    123
Wed   9  19  18    413
Thu   4   6  12    212
Fri   1   6   7    137